baseurl = "/"
languageCode = "en-us"
title = "iqis"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
hasCJKLanguage = true
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = ""

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

#[[menu.main]]
#    name = "Categories"
#    url = "categories/"
#    weight = 1
[[menu.main]]
    name = "Vitae"
    url = "/vitae"
    weight = 2

[[menu.feed]]
    name = "rss"
    url = "/index.xml"

[params]
    description = "on data science, advanced media analytics with R, Shiny"
    footer = '&copy; <script type="text/javascript">document.write(new Date().getFullYear());</script> Siqi Zhang <a href = "https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>'
    custom_css = ["css/theme-override.css"]
